Book setup
LambdaBooks/clojurescript-unraveled pull request #1
Opened 2017-02-13 13:18 UTC by denysdovhan

Setup a new book

2017-02-13 13:22 UTC, denysdovhan reviewed
Варто перевірити переклад `SUMMARY.md`

2017-02-13 13:22 UTC, denysdovhan commented on SUMMARY.md
> +  * Потокові макроси
@roman01la не певний, що я тут правильно переклав.

2017-02-13 13:22 UTC, denysdovhan commented on SUMMARY.md
> +  * Умови читача
@roman01la тут теж варто перевірити.

2017-02-13 13:22 UTC, denysdovhan commented on SUMMARY.md
> +* Мова (поглиблені теми)
@roman01la це теж варто перевірити

2017-02-13 13:47 UTC, denysdovhan commented on README.md
> +* **4149 4378 5069 5501** — Lambda Books (підтримка перекладу)
@roman01la можеш дописати тут свій рахунок

2017-02-13 14:27 UTC, alexclosed commented on README.md
> +Відкрита книга про ClojureScript. Читати оригінальну онлайн–версію можна [тут](http://funcool.github.io/clojurescript-unraveled/). Електронна версія оригінальної книги ( у форматах `epub` та `mobi`)
Ви можете прочитати онлайн-версію оригіналу тут.
Електронну  версію оригіналу ви можете завантажити на ..., де також можна підтримати нас або купити авторам пива

2017-02-13 14:27 UTC, alexclosed commented on README.md
> +Ця книга повинна служити як:
Ця книга - це: (мені здається так було б краще)

2017-02-13 14:27 UTC, alexclosed commented on README.md
> +* [_Олександр Закритий_](https://twitter.com/nevusnews) — коректор.
Мімімі ^^

2017-02-13 14:27 UTC, alexclosed commented on SUMMARY.md
> +  * Колекції типів
Локали

2017-02-13 14:37 UTC, roman01la commented on SUMMARY.md
> +  * Потокові макроси
Думаю нормально, в русском языке так же говорят.

2017-02-13 14:41 UTC, roman01la commented on SUMMARY.md
> +  * Умови читача
слово «reader» действительно используется как «читач»
нужно подумать над правильным словосочетанием

2017-02-13 14:42 UTC, roman01la commented on SUMMARY.md
> +* Мова (поглиблені теми)
думаю нормально

2017-02-13 14:43 UTC, roman01la commented on README.md
> +* **4149 4378 5069 5501** — Lambda Books (підтримка перекладу)
ок

2017-02-13 14:47 UTC, roman01la commented on SUMMARY.md
> +  * Колекції типів
«Locals» здесь как «локальные переменные», но в Clojure нету понятия переменной. Нужно как-то обыграть что ли.

2017-02-14 12:32 UTC, roman01la requested changes

2017-02-14 12:32 UTC, roman01la commented on README.md
> +- детальне керівництво до компілятора ClojureScript та інструментів довкола нього;
детальне керівництво до інструментів розробки

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Змінні
В языке нет переменных, они так и называются «вар»/«вары»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Контроль над ходом виконання
«Керування потоком виконання»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Істиності
«Істинність»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Колекції типів
«локальні прив'язки» local bindings, (locals сокращение)

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Колекції типів
«Типи колекцій»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Контроль над станом
«Керування станом»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +* Інструменти та компілятор
інструментарій

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Початок роботи з компілятором
«Починаємо працювати з компілятором»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Контроль над залежностями
«Керування залежностями»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Юніт–тестування
«Модульне тестування»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Трансдюсери
«Перетворювачі» ?

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Transients
«Перехідні структури даних»

2017-02-14 12:32 UTC, roman01la commented on SUMMARY.md
> +  * Базові протоколи
«Основні протоколи»

2017-02-14 20:46 UTC, merged