02 introduction
LambdaBooks/clojurescript-unraveled pull request #42
Opened 2017-02-17 10:27 UTC by roman01la

Драфт перевода раздела ”02 Introduction” #4

2017-02-17 10:39 UTC, denysdovhan requested changes
Треба виправити і зліпити останні два коміти в один, щоб був правильний діфф для рев’юверів.

2017-02-17 10:39 UTC, denysdovhan commented on manuscript/02-Introduction.md
> +> — <cite>Річ Хікі</cite>
> Річ Хікі (Rich Hickey)

Імена перекладаємо і в дужках вказуємо оригінальне написання.

2017-02-17 10:39 UTC, denysdovhan commented on manuscript/02-Introduction.md
>  > — <cite>Rich Hickey</cite>
> Річ Хікі (Rich Hickey)

2017-02-19 08:16 UTC, alexclosed commented on manuscript/02-Introduction.md
> +На відміну від інших мов, які призначені _компілюватися_ в JavaScript (такі як TypeScript, FunScript або CoffeScript), ClojureScript створена використовувати JavaScript як байткод. Це дуже надійна і
(Такі,(!) як тайпскріпт, фанскріпт...)
Дуже надійна **та** безпечна мова,(!) що

2017-02-19 08:16 UTC, alexclosed commented on manuscript/02-Introduction.md
> +Ще одна велика відмінність (і на нашу думку перевага) від інших мов полягає в тому, що Clojure призначена бути гостьовою мовою. Це мова без власної віртуальної машині, яка може бути легко адаптована
**ще однією великою відмінністю (і,(!) на нашу думку,(!) перевагою) від інших мов є те**,  що (імхо, але пуктуація норм.
Власної віртуальної машин**и**
(А, отже,(!) і для клоюрескріпт)

2017-02-19 08:16 UTC, alexclosed commented on manuscript/02-Introduction.md
> +Перед тим як ми розпочнемо, давайте резюмуємо деякі з основних ідей в ClojureScript. Не переймайтеся якщо ви не розумієте їх зараз, по ходу книги вони стануть більш зрозуміліші.
Перед тим,(!) як ми розпочнемо
Не переймайтеся,(!) якщо ви не розумієте їх зараз -(!) по ходу книги вони стануть більш **зрозумілі**

2017-02-19 08:16 UTC, alexclosed commented on manuscript/02-Introduction.md
> +* ClojureScript нав'язує парадигму функціонального програмування з її ідеями та ідіомами. Але хоч вона і підтримує функціональне програмування, в ній все ж більше прагматизму ніж бажання переслідуват
Більше прагматизму,(!)

2017-02-19 08:16 UTC, alexclosed commented on manuscript/02-Introduction.md
> +* Вона має поліморфізм на основі типів і значень, що елегантно вирішують проблему вираження.
Має поліморфізм, що елегантно вирішу**є**

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +Ще одна велика відмінність (і на нашу думку перевага) від інших мов полягає в тому, що Clojure призначена бути гостьовою мовою. Це мова без власної віртуальної машині, яка може бути легко адаптована
яка може легко **адаптуватися** до нюансів середовища виконання.

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +* ClojureScript нав'язує парадигму функціонального програмування з її ідеями та ідіомами. Але хоч вона і підтримує функціональне програмування, в ній все ж більше прагматизму ніж бажання переслідуват
замість резюмуємо краще **підсумуємо** основні ідеї.

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +* ClojureScript нав'язує парадигму функціонального програмування з її ідеями та ідіомами. Але хоч вона і підтримує функціональне програмування, в ній все ж більше прагматизму ніж бажання переслідуват
тор**Е**тичну

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +* ClojureScript нав'язує парадигму функціонального програмування з її ідеями та ідіомами. Але хоч вона і підтримує функціональне програмування, в ній все ж більше прагматизму ніж бажання переслідуват
крапку з комою після кожного пункту, і, починаючи від 2 пункту, перше слово з малої букви

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +* Заохочує до програмування використовуючи незмінні дані, пропонуючи високоефективні та розвинені імплементації незмінних колекцій.
Заохочує до використання незмінних даних в програмуванні та пропонує високоефективні та розвинені імплементації незмінних колекцій

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +* Це діалект Lisp, тому програми написані структурами даних самої мови, ця властивість відома як _гомоіконність_, що робить метапрограмування (програми, які пишуть програми) дуже простим.
тут варто зробити 2 речення.
мови . Ця властивість ..

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +> Ми можемо робити точно таке ж програмне забезпечення, що ми робимо сьогодні, викорустовуючи значно простіші речі — значно простіші мови, інструменти, методи, підходи.
речі : (!) значно простіші мови, інструменти, методи, підходи.

2017-02-19 09:58 UTC, Mariannach commented on manuscript/02-Introduction.md
> +Ми сподіваємося, що вам сподобається книга і ClojureScript принесе таку ж радість і натхнення, що принесла й нам.
**яку** принесла й нам.

2017-02-21 07:43 UTC, AMashoshyna commented on manuscript/02-Introduction.md
> +* Це діалект Lisp, тому програми написані структурами даних самої мови, ця властивість відома як _гомоіконність_, що робить метапрограмування (програми, які пишуть програми) дуже простим.
Може "гомоіконічність"? 
В лінгвістиці та семіотиці є споріднений термін "іконічність".

@Mariannach як на вашу думку?

2017-02-21 08:52 UTC, merged