03 01 first steps lisp
LambdaBooks/clojurescript-unraveled pull request #45
Opened 2017-02-18 00:06 UTC by AMashoshyna

Draft translation “03-01 First steps with Lisp syntax” [#6](https://github.com/LambdaBooks/clojurescript-unraveled/issues/6)

2017-02-19 20:08 UTC, roman01la requested changes

2017-02-19 20:08 UTC, roman01la commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Мова Lisp була розроблена Джоном МакКарті у 1958 році і на сьогодні є однією з найстарших мов програмування, що досі використовуються. Від Lisp походить велика кількість інших мов, які називають діал
Clojure(Script) дода**ла**

2017-02-19 20:08 UTC, roman01la commented on manuscript/03-01-First-steps-with-List-syntax.md
> +У ClojureScript список, першим елементом якого є функція, використовується для виклику функції. У наступному прикладі ми викликаємо функцію додавання із троьма аргументами. Зверніть увагу на те, що у
трьома

2017-02-19 20:08 UTC, roman01la commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Для відокремлення викликів функцій від списків даних ми можемо цитувати списки за допомогою оператора `quote` і тим самим заборонити їх обчислення. Цитовані списки сприймаються компілятором як дані,
за допомогою **функції** `quote`
(в языке нету операторов)

2017-02-19 20:08 UTC, roman01la commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Для відокремлення викликів функцій від списків даних ми можемо цитувати списки за допомогою оператора `quote` і тим самим заборонити їх обчислення. Цитовані списки сприймаються компілятором як дані,
в этом контексте вместо **відокремлення** больше подходит что-то вроде **розрізнення**

2017-02-19 21:22 UTC, Mariannach commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Мова Lisp була розроблена Джоном МакКарті у 1958 році і на сьогодні є однією з найстарших мов програмування, що досі використовуються. Від Lisp походить велика кількість інших мов, які називають діал
з **найдавніших** мов ..

в кінці абзацу буква І .

2017-02-19 21:22 UTC, Mariannach commented on manuscript/03-01-First-steps-with-List-syntax.md
> +У ClojureScript список, першим елементом якого є функція, використовується для виклику функції. У наступному прикладі ми викликаємо функцію додавання із троьма аргументами. Зверніть увагу на те, що у
немає, **а є** лише функції

2017-02-19 21:22 UTC, Mariannach commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Синтаксис ClojureScript  не обмежується списками. Повну інформацію з цього питання ви знайдете у подальших розділах, а зараз лише наведемо приклад використання вектора (у прямокутних дужках) для визн
замість  повну краще **детальну** інформацію

2017-02-19 22:07 UTC, alexclosed commented on manuscript/03-01-First-steps-with-List-syntax.md
> +У ClojureScript список, першим елементом якого є функція, використовується для виклику функції. У наступному прикладі ми викликаємо функцію додавання із троьма аргументами. Зверніть увагу на те, що у
Або ж так "операторів у лісп немає -(!) лише функції"

2017-02-19 22:07 UTC, alexclosed commented on manuscript/03-01-First-steps-with-List-syntax.md
> +Це майже усе, що нам потрібно знати про синтаксис для написання коду на ClojureScript, а також на будь-якому іншому діалекті Lisp. Мови, які підтримують написання коду з використанням власних структу
Мови, які підтримують написання коду з використанням власних структур даних (їх називають _гомоіконічними_),(!) мають багато переваг ...

Зокрема генерація коду за допомогою макросів у таких мовах простіша,(!) ніж у інших...

2017-02-20 21:38 UTC, AMashoshyna commented
apply review fixes from @roman01la @Mariannach @alexclosed

2017-02-21 08:42 UTC, denysdovhan requested changes
Use Markdown, not ADOC

2017-02-21 08:42 UTC, denysdovhan commented on manuscript/03-01-First-steps-with-List-syntax.md
>  [source, clojure]
All blocks of code should be written in Markdown, not in ADOC.
Please, read [CONTRIBUTING.md](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/CONTRIBUTING.md) and fix that.

2017-02-21 08:42 UTC, denysdovhan commented on manuscript/03-01-First-steps-with-List-syntax.md
>  [source, clojure]
here the same

2017-02-21 08:42 UTC, denysdovhan commented on manuscript/03-01-First-steps-with-List-syntax.md
>  [source, clojure]
and here again

2017-02-22 20:59 UTC, denysdovhan commented on manuscript/03-01-First-steps-with-List-syntax.md
> +```clojure
There is a `cljs`, btw.
Nevermind, I'll fix that by myself.

2017-02-23 10:51 UTC, roman01la commented on manuscript/03-01-First-steps-with-List-syntax.md
> +```clojure
@denysdovhan I believe both `clojure` and `cljs` highlighting are the same. I'm usually using `clojure`.

2017-02-23 11:02 UTC, denysdovhan commented on manuscript/03-01-First-steps-with-List-syntax.md
> +```clojure
@roman01la there is a corresponding item (13th) in [CONTRIBUTING.md](https://github.com/LambdaBooks/clojurescript-unraveled/blob/master/CONTRIBUTING.md#Правила-оформлення). Moreover, `cljs` is more specific.

2017-02-23 11:44 UTC, denysdovhan approved these changes

2017-02-23 11:45 UTC, denysdovhan commented
Merged in 078b6d763996b6120586c32680e8a73de7ba01fe

2017-02-23 11:45 UTC, closed without merging