Translation of “03-07 Locals, Blocks, and Loops”
LambdaBooks/clojurescript-unraveled pull request #56
Opened 2017-03-07 12:22 UTC by roman01la

Translation of “03-07 Locals, Blocks, and Loops” #12

2017-03-07 21:00 UTC, denysdovhan requested changes
Є кілька зауважень: зайві абзаци, перекладений вивід `println` і тд.

2017-03-07 21:00 UTC, denysdovhan commented on manuscript/03-07-Locals-Blocks-and-Loops.md
>  Many of the common patterns for which `for` is used in other languages are achieved
Зайвий абзац. Нижче є той же абзац, але перекладений.

2017-03-07 21:00 UTC, denysdovhan commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +;; Циклічный виклик з 0
Думаю це не варто перекладати, адже це вивід результат виклику 61-го рядка.

2017-03-07 21:00 UTC, denysdovhan commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +;; Циклічный виклик з 0
Тут, думаю, теж не варто перекладати результат виводу з `println`

2017-03-07 21:00 UTC, denysdovhan commented on manuscript/03-07-Locals-Blocks-and-Loops.md
>  graph the equation `y&#160;=&#160;3x&#160;+&#160;5` for a set of _x_ values, you
Зайвий неперекладений абзац. Після нього слідує той же, але перекладений.

2017-03-07 21:00 UTC, denysdovhan commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Після обчислення повертається `nil`.
Після обчислення ця функція повертає `nil`.

2017-03-08 08:53 UTC, AMashoshyna commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Функціональний підхід в ClojureScript не обумовлює наявність стандартного механізму для створення циклів за допомогою спеціальних конструкцій, як наприклад цикл `for` у JavaScript. В ClojureScript ци
Можна так:
"Функціональний підхід передбачає відсутніть стандартних, добре відомих циклів на базі спеціальних виразів, зокрема, аналогів циклу 'for' у JavaScript."

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +В ClojureScript немає поняття змінної, як в мовах родини ALGOL, але є так звані локальні зв'язування (для зручності будемо називати їх також змінними). Локальні змінні, за звичай, не змінюють свої зн
**зазвичай**

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Тіло виразу `let`, про який ми говорили раніше, дуже схоже на вираз `do` тим, що воно теж приймає декілька виразів. Насправді `let` містить в собі неявний `do`.
Насправді ,(!)

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Функціональний підхід в ClojureScript не передбачає наявність стандартного механізму для створення циклів за допомогою спеціальних конструкцій, як наприклад цикл `for` у JavaScript. В ClojureScript ц
**ВИ**рішення проблеми ..

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Багато підходів, що використовують цикл `for` в інших мовах, досягаються за допомогою функцій вищого порядку — функції, що приймають інші функції.
порядку - **таких**, що приймають ..

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Давайте розберемось як можна виразити цикл за допомогою форм `loop` та `recur`. `loop` містить вектор локальних змінних (так само, як `let`) та вираз, що ними оперує, а `recur` циклічно викликає `loo
.. розберемось,(!) як ..

а recur -(!) циклічно ..

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +У цьому прикладі ми зв'язуємо значення `0` з символом `x` і виконуємо тіло циклу — вираз, у якому є умова. Під час першого виконання цього виразу, умова не справджується, тому `recur` повторює цикл в
**З** результатом ..


Так буде продовжкватись ,(!) доки... з рекурсії,(!) повернувши результат.

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +В імперативних мовах програмування цикл `for` часто використовується для ітерування даних і їх перетворення, за звичай це роблять у наступних випадках:
**зазвичай**,(!) це роблять,(!) **коли потрібно** :

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +- Відфільтрувати значення у колекції по деякому критерію
**за певним критерієм**

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +- Перетворити колекцію у значення, коли кожна наступна ітерація залежить від результаті минулої
результат**У**

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +
Кожен пунктик з **маленької літери**, в кінці кожного пункту - **крапка з комою**, в останньому - **крапка**.

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Першим параметром в `map` може бути будь-яка функція що приймає один аргумент і повертає значення. Наприклад, якщо у вас був би застосунок для створення графіків і вам потрібно було б створити графік
функція ,(!) що ..

якщо **Б** у вас був застосунок ..

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +`reduce` приймає будь-яку функцію, що приймає _два_ аргументи та повертає значення. Першим аргументом буде згорнуте значення, другим — наступне значення в колекції. Функція повертає значення, що буде
Функція повертає значення, що буде згорнутим**(!)** (першим аргументом) в наступній ітерації.

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +В ClojureScript вираз `for` використовується не для ітерування, а для створення послідовностей. Ця операція також відома, як «sequence comprehension». В цьому розділі ми дізнаємось як вона працює та
відома (!) як «sequence comprehension».

ми дізнаємось,(!) як вона працює ..

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +У цьому прикладі символ `x` зв'язаний з поточним значенням з вектору `[1 2 3]`, а результатом обчислення усього виразу буде послідовність векторів з двох елементів, в яких другий елемент — квадрат по
вектор**А**

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Після визначення локальних зв'язувань для поточних значень можна використати три модифікатори: `:let` для створення додаткових локальних зв'язувань, `:while` для виходу с процесу створення колекції,
let`  -(!) для

:while`  - (!)для виходу **З** процесу

`:when` -(!) для фільтрування

2017-03-11 10:23 UTC, Mariannach commented on manuscript/03-07-Locals-Blocks-and-Loops.md
> +Ми можемо використати модифікатор `:while` щоб створити умову, яка призведе до виходу з процесу створення колекції коли результатом її обчислення буде логічне `false`. Ось приклад:
модифікатор `:while` ,(!) щоб .... колекції ,(!) коли ..

2017-03-19 13:46 UTC, denysdovhan approved these changes

2017-03-20 17:33 UTC, merged