Translation of “03-08 Collection types” #13
LambdaBooks/clojurescript-unraveled pull request #58
Opened 2017-03-08 12:22 UTC by AMashoshyna

Translation of “03-08 Collection types” [#13](https://github.com/LambdaBooks/clojurescript-unraveled/issues/13)

2017-03-19 18:40 UTC, Mariannach requested changes

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Продемонструємо дію цього принципу на наступному прикладі: спробуємо додати нове значення до вектора за допомогою операції `conj` (conjoin).
**У** наступному прикладі..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Стійка структура даних - це така структура, що при трансформації повертає нову версію самої себе та лишається не зміненою.  Завдяки техніці _structural sharing_  (спільне користування структурами) Cl
це структура, **ЯКА** при трансформації ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Як видно з прикладу, ми додали у початок списку `xs` нове значення за допомогою функції `cons` (construct) і отримали новий список `ys`, що містить доданий елемент. Далі, ми викликали функцію  `rest`
ці значення **є таким самим об'єктом** у пам'яті, ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +`next` - операція, схожа на `rest`, але `next` повертає значення  `nil`, якщо передати їй послідовність, що містить лише один елемент або не містить жодного.
`next` -(!) повертає значення

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Зауважимо, що у такому випадку порожня послідовність як результат роботи `rest` буде обчислена як логічне true,  у той час як `nil`, що буде результатом роботи `next`, обчислиться як логічне `false`.
послідовність,(!) як результат роботи `rest` ,(!) буде обчислена

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +##### Використання багатозначност `nil`
багатозначност**І**

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Отож, `seq` при виклику з порожньою колекцією повертає значення `nil`, а `nil` обчислюється як логічне `false`. Ми можеме скоритатися цим знанням для виявлення порожніх колекцій. Такий прийом називає
`seq` ,(!)  при виклику з порожньою колекцією  ..

можем**О**

**називають** використанням багатозначності

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Можливо, ви вже помітили, що функції, які маніпулюють послідовностями, можуть бути викликані із порожніми колекціями, та навіть із значеннями  `nil`, без помилки: у таких випадках вони лише повертают
без помилки.(!) У таких випадках ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Ми бачили приклади із найбільш часто вживаними функціями, що працюють із колекціями -  `map`, `filter`, та `reduce`. Та насправді простір імен стандартної бібліотеки ClojureScript  пропонує велику кі
**найчастіше** вживаними функціями, ..

`filter`(!) та `reduce`

Та,(!) насправді,(!) простір імен ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Предиката  `coll?` дозволяє перевірити, чи є певний елемент колекцією:
перевірити(!) чи є певний елемент ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Існують схожі за функціональністю предикати для перевірки, чи є певне значення послідовністю (`seq?`) або спископодібним типом (`seqable?`):
перевірки (!) чи є ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Предиката  `empty?` повертає значеня true,  якщо її аргумент - порожня колекція:
тут треба  true виділити, здається.

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Операція `conj` додає елементи до колекцій. Нові елементи розміщуються на тих позиціях колекції, де це найбільш продуктивно для певного типу колекцій. При цьому не кожна колекція має визначений поряд
де це буде найбільш продуктивним для певного типу колекцій.

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Якщо викликати  `(range)` без аргументів, то результатом буде нескінченна послідовність цілих чисел. Не відтворюйте цю пораду у REPL, якщо не готові чекати на результат дуже, дуже довго, бо REPL праг
на результат дуже довго, ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Додавання елементів до "голови" списку займає постійний час, тому опеарція `conj` додає нові елементи саме на початку.
займає **певний** час

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Зверніть увагу: використати фунцію  `assoc` можна із ключем, що вже міститься у векторі, або якщо задана позиція буде останньою у векторі:
Зверніть увагу,(!) використати фунцію

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Може здатися дивним, але асоційовані структури даних також можуть бути викликані як функції. Вектору можна передати ключ та отримати повʼязане за цим ключем значення. Якщо заданий ключ відстуній, з'я
**З** цим ключем ..

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +ClojureScript також має сортовані хеш-мапи, які за поведінкою схожі на несортовані мапи, але при ітеруванні зберігають порядок. Сортовану мапу із звичайним впорядкуванням можно створити за допомогою
можн**А**

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Для створення мапи із довільним впорядкуванням ми можемо передати функцію `sorted-map-by`, яка використовується при порівнянні елементів. Функції для порівняння приймають два елемента та повертають з
елемент**И**

(якщо елементи рівні) (!) або

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Множини виступають як доступні лише для читання асоціативні дані, що поєднують значення, що в них містяться, до себе самих. У ClojureScript, окрім `nil` та `false` усі значення обчислюються як логічн
**приєднують** значення, **ЯКЕ** в них містяться, до себе самих

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +У ClojureScript підтримує стійкі та незмінні черги. Черги - найменш розповсюджений тип колекцій. Створити чергу можна за допомогою літерального синтаксису `#queue []`, але зручних функцій-конструктор
(!) ClojureScript підтримує стійкі та незмінні черги.

2017-03-19 18:40 UTC, Mariannach commented on manuscript/03-08-Collection-types.md
> +Черги використовуються менш часто, ніж списки та вектори, але знання про їхнє існування у  ClojureScript може стати у нагоді у певних випадках.
у нагоді **В** певних випадках.

2017-03-19 23:21 UTC, AMashoshyna commented on manuscript/03-08-Collection-types.md
> +Додавання елементів до "голови" списку займає постійний час, тому опеарція `conj` додає нові елементи саме на початку.
А можна так: "Додавання елементів до "голови" списку відбувається за постійний час"? 

Мені здається, що "певний час" не підходить як переклад терміну "constant time". Варіант "відбувається за постійний час" - це з Вікіпедії.

2017-03-20 08:15 UTC, denysdovhan approved these changes
Маю кілька зауважень, але виправлю сам.

2017-03-20 08:18 UTC, AMashoshyna commented
@denysdovhan дякую, подивлюся правки

2017-03-20 17:45 UTC, merged