Translation for “03-09 Destructuring”
LambdaBooks/clojurescript-unraveled pull request #59
Opened 2017-03-09 11:05 UTC by roman01la

draft translation for “03-09 Destructuring” #14

2017-03-14 14:31 UTC, OksanaChmil requested changes

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Давайте розглянемо приклад, щоб зрозуміти в яких випадках деструктурування може бути корисним. Звичайно якщо вам треба прочитати лише перший та третій елемент з колекції, це можна зробити за допомого
Звичайно, (!) якщо вам

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +У цьому прикладі `[fst _ thrd]` — форма деструктурування. Вона представлена у вигляді вектору, що використовується для зв'язування значень в колекції з символами `fst` і `thrd` відповідно до індексів
значень, (!) які нам **не потрібні**

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Зверніть увагу, що деструктурування не обмежене зв'язуванням у формі `let`; воно працює майже усюди де можливо зв'язати значення з символом, наприклад у формах `for` та `doseq`, а також у аргументах
усюди, (!) де можливо

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Зверніть увагу, що деструктурування не обмежене зв'язуванням у формі `let`; воно працює майже усюди де можливо зв'язати значення з символом, наприклад у формах `for` та `doseq`, а також у аргументах
наприклад, (!) у формах

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Деструктурування по позиції в колекції за допомогою вектору добре підходить для вичитування значень з індексованих послідовностей, але інколи ми не хочемо відкидати інші аргументи послідовності. Симв
Деструктурування **за позицією** в колекції **з** допомогою **вектора**

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Деструктурування по позиції в колекції за допомогою вектору добре підходить для вичитування значень з індексованих послідовностей, але інколи ми не хочемо відкидати інші аргументи послідовності. Симв
послідовність так само

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Деструктурування по позиції в колекції за допомогою вектору добре підходить для вичитування значень з індексованих послідовностей, але інколи ми не хочемо відкидати інші аргументи послідовності. Симв
**варіаційних**(?) функцій

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +У цьому прикладі перше значення в колекції, з індексом `0`, прив'язано до символу `fst`, друге, з індексом `1`, до `snd`, а усі інші, починаючи з індексу `2` і до кінця, до символу `more`.
**прив'язане** до символу `fst`, друге, з індексом `1`,  — до `snd`, а усі інші, починаючи з індексу `2` і до кінця,  — до символу `more`.

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +В асоціативних структурах даних ключами можуть бути не лише ключові слова. Числа, рядки, символи та інші структури даних теж можуть бути ключами, тому ми також можемо використовувити їх у деструктуру
можемо **використовувати** їх у деструктуруванні

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +В асоціативних структурах даних ключами можуть бути не лише ключові слова. Числа, рядки, символи та інші структури даних теж можуть бути ключами, тому ми також можемо використовувити їх у деструктуру
у лапки,(!) щоб представити як структуру даних, а не змінну,(!) у якої є деяке

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +За звичай значення у деструктуруванні мапи зв'язують з символами з таким же ім'ям, як і ключі у цій мапі (наприклад, значення по ключу `:language` до символу `language`). Так як ключами звичайно бува
**Зазвичай**

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +За звичай значення у деструктуруванні мапи зв'язують з символами з таким же ім'ям, як і ключі у цій мапі (наприклад, значення по ключу `:language` до символу `language`). Так як ключами звичайно бува
**Оскільки** ключами звичайно

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Як ви можете бачити, ключове слово `:keys` та вектор символів утворюють локальні змінні зі значеннями відповідно до ключів у мапі. Символи у векторі повинні мати таке ж саме ім'я як і відповідні ключ
мати таке ж ім'я,(!) як і відповідні

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Скорочена форма для рядків та символів працює точно так як і `:keys`, але з використанням `:strs` та `:syms` відповідно:
точно так,(!) як і

2017-03-14 14:31 UTC, OksanaChmil commented on manuscript/03-09-Destructuring.md
> +Цікавою особливістю деструктурування є те, що форми можна вкладувати для вичитування вкладених значень, при цьому це легко читається, так як форма деструктурування описує структуру самої колекції:
читається, **оскільки** форма

2017-03-20 17:46 UTC, denysdovhan approved these changes

2017-03-20 17:52 UTC, merged