Translate “03-13 Abstractions and Polymorphism”
LambdaBooks/clojurescript-unraveled pull request #63
Opened 2017-03-22 10:02 UTC by roman01la

Translate “03-13 Abstractions and Polymorphism” #18

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ви напевно не раз були в такій ситуації: ви створили абстракцію (наприклад за допомогою інтерфейсів) для бізнес логіки, з часом у вас виникає потреба працювати з іншим модулем, який ви не контролюєте
Ви,(!) напевно,(!)
Наприклад,(!) за доп інтерфейсів
Бізнес-логіки(!)
Вирішиили зробити адаптер,(!) проксі або застосувати інші підходи,(!) які

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми не можемо довіряти мовам, що дозволяють переписувати методи, які ви використовуєте у себе, іншими бібліотеками; коли таке трапляється поведінка програми може бути непередбаченою.
Коли таке трапляється,(!) поведінка може...

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Такі симптоми називають проблемою виразу (expression problem); дізнайтеся більше за посиланням http://en.wikipedia.org/wiki/Expression_problem
Такі симптоми **зазвичай** називають

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  "Рядок документації описуючий протокол."
Рядок документації, **який** описує протокол

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +> ЗАУВАЖЕННЯ: Префікс «I» часто використовується для розрізнення протоколів та типів за іменем. В громаді Clojure розробників існує багато різних думок на рахунок того, як повинен використовуватись п
В громаді клоюр-розробників
На нашу думку,(!) це
У той же час,(!) не використовувати

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +З точки зору користувача, функції протоколів — це звичайні функції, що створені у тому ж просторі імен де і сам протокол. Це дає простий та легкий спосіб уникнення конфліктів між протоколами з однако
У тому ж просторі,(!) де і

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Майже завжди ви будете використовувати макроси `extend-protocol` або `extend-type`. Ось як виглядає синтаксис `extend-type`:
Ось,(!) як

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ви могли помітити, що ми використали символ `string` замість `js/String` коли розширювали протоколом тип рядок. Це тому, що типи з JavaScript не можна розширювати. Якщо ви спробуєте розширити тип `js
Використали символ замість,(!) коли
Тип-рядок
Якщо ви спробуєте розширити тип,(!) компілятор сповістить про це,(!) показавши помилку

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +`extend-protocol` працює навпаки; маючи протокол, цей макрос дозволяє додати імплементацію до декількох типів одразу. Ось як виглядає синтаксис:
Ось,(!) як виглядає синтаксис

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Що тут відбувається? У цьому випадку тип `set` імплементує протокол `IFn`, що є абстракцією для функцій або всього, що може бути викликаним як функція. Таким чином `set` може бути використаний як пре
Таким чином,(!) сет може бути

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми одержали помилку, бо тип `RegExp` не імплементує протокол `IFn`, тому він і не може бути використаний як функція. Але це можна легко змінити:
Використаний,(!) як функція

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Давайте проаналізуємо цей приклад: ми розширили тип `js/RegExp` імплементацією функції `invoke` у протоколі `IFn`. Щоб регулярний вираз `а` поводився як функція, в імплементації нам треба виконати оп
Поводився,(!) як функція

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Тепер ви можете використати регулярний вираз як предикату, наприклад в функції `filter`:
Як предикату, наприклад,(!) в функції

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Наприклад ось так ми можемо перевірити, що `set` імплементує протокол `IFn`:
Наприклад,(!)

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Раніше ми говорили про протоколи, що вирішують часту проблему поліморфізму: визначення по типу. Та за деяких обставин протоколи можуть обмежувати. Для таких випадків існують _мультіметоди_.
Мульт**и**методи

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +_Мультіметоди_ не обмежені визначенням по типу; вони дозволяють визначати по типам декількох аргументів та значенню. Вони також дозволяють утворювати спеціалізовані (ad-hoc) ієрархії. Як і протоколи,
Мульт**и**методи

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Для створення мультіметодів використовують форми `defmulti` та `defmethod`. Мультіметод створюється за допомогою `defmulti` і приймає функцію, що визначає метод. Ось як це виглядає:
Мцльт**и**методів
Ось,(!) як

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  у якого встановлено значення за замовчуванням `:en`"
Від значення ключа,(!) у якого

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Анонімна функція у `defmulti` — функція, що визначає який з методів повинен бути викликаний. Ця функція буде викликана кожного разу, коли ми викликаємо `say-hello` і повинна повертати деяке значення,
Функція, що визначає,(!) який

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
І нарешті,(!)

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  (str "Привіт " (:name person "Анонімний")))
Нейм персон "анонім"

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Якщо викликати нашу функцію і передати в неї мапу з ключами `:locale` та `:name`, мультіметод спочатку викличе визначаючу функцію, щоб отримати визначаюче значення, а потім знайде імплементацію для ц
Мульт**и**метод

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Якщо імплементації за замовчунням немає, буде виведена помилка з повідомленням про те, що для використаного значення відсутня імплементація в мультіметоді.
Мульт**и**методі

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В _ClojureScript_ ієрархії використовуються для побудови відносин у системі. Ієрархії створюються як відносини між такими об'єктами як символи, ключові слова та типи.
Ієрархії створюються,(!) як відносини між

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В залежності від ваших потреб ієрархії можна будувати локально чи глобально. Як і мультіметоди ієрархії не обмежені одним простором імен. Їх можна розширювати з будь-якого простору імен.
В залежності від ваших потреб,(!) ієрархії
Як і мультиметоди,(!) ієрархії

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Глобальний простір імен більш обмежений, що зроблено навмисно. Ключові слова та символи, що не прив'язані до простору імен не можуть бути використані у глобальній ієрархії. Така поведінка допомагає у
Ключові слова та символи, що не прив'язані до простору імен,(!) можуть бути
Несподіваних ситуацій,(!) коли

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми створили набір зв'язків між іменованими ключовими словами. У цьому випадку `::circle` та `::box` є дочірніми для `::shape`.
У цьому випадку,(!)

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Як ви можете бачити, в локальних ієрархіях ми можемо використовувати нормальні (не іменовані) ключові слова, а функція `isa?` повертає `false` якщо в неї не передати ієрархію.
**неіменовані**
Функція повертає,(!) якщо

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Однією із значних переваг ієрархій є те, що вони дуже добре працюють з мультіметодами. Мультіметоди використовують функцію `isa?` на останньому етапі визначення методу.
Однією **зі** значних переваг

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Давайте розглянемо приклад щоб зрозуміти, що це означає. Спочатку ми створюємо мультіметод за допомогою форми `defmulti`:
Розглянемо приклад,(!) щоб зрозуміти,(!) - без "давайте": занадто багато у цьому тексті

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Далі ми створюємо імплементації мультіметоду як за звичай, за допомогою `defmethod`:
Як зазвичай

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Тепер подивимось, що відбудеться коли ми викличемо мультіметод:
Що відбувається,(!) коли ми викличемо мульт**и**метод

2017-04-29 10:09 UTC, alexclosed commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Все працює як і очікувалось; мультіметод викликає імплементацію по ключовому слову `:box`. Тепер подивимось, що буде якщо викликати мультіметод з ключовим словом `:circle`, для якого імплементація ві
Все працює,(!) як і очікувалось
Що буде,(!) якщо викликати мульт**и**метод

2017-04-30 06:03 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми одержали помилку, бо тип `RegExp` не імплементує протокол `IFn`, тому він і не може бути використаний як функція. Але це можна легко змінити:
@alexclosed не потрібно тут коми)
Використаний як функція

2017-04-30 06:05 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Давайте проаналізуємо цей приклад: ми розширили тип `js/RegExp` імплементацією функції `invoke` у протоколі `IFn`. Щоб регулярний вираз `а` поводився як функція, в імплементації нам треба виконати оп
тут також не треба коми

2017-04-30 06:07 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Раніше ми говорили про протоколи, що вирішують часту проблему поліморфізму: визначення по типу. Та за деяких обставин протоколи можуть обмежувати. Для таких випадків існують _мультіметоди_.
Раніше ми говорили про протоколи, що вирішують  **проблему поліморфізму, яка трапляється досить часто -(!) визначення ЗА типОМ.**

2017-04-30 06:08 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +_Мультіметоди_ не обмежені визначенням по типу; вони дозволяють визначати по типам декількох аргументів та значенню. Вони також дозволяють утворювати спеціалізовані (ad-hoc) ієрархії. Як і протоколи,
**за типом**

2017-04-30 06:15 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В _ClojureScript_ ієрархії використовуються для побудови відносин у системі. Ієрархії створюються як відносини між такими об'єктами як символи, ключові слова та типи.
Ієрархії **створюють відносини** між такими об'єктами як символи, ключові слова та типи.

2017-04-30 06:16 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В залежності від ваших потреб ієрархії можна будувати локально чи глобально. Як і мультіметоди ієрархії не обмежені одним простором імен. Їх можна розширювати з будь-якого простору імен.
**Залежно від ваших потреб**, ієрархії можна будувати локально чи глобально.
(в залежності - калька)

2017-04-30 06:17 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Однією із значних переваг ієрархій є те, що вони дуже добре працюють з мультіметодами. Мультіметоди використовують функцію `isa?` на останньому етапі визначення методу.
мультИмеоди

2017-04-30 06:19 UTC, Mariannach commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Далі ми створюємо імплементації мультіметоду як за звичай, за допомогою `defmethod`:
мультИметоду,(!) як зазвичай, за допомогою

2017-06-05 11:49 UTC, denysdovhan requested changes

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ви напевно не раз були в такій ситуації: ви створили абстракцію (наприклад за допомогою інтерфейсів) для бізнес логіки, з часом у вас виникає потреба працювати з іншим модулем, який ви не контролюєте
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми не можемо довіряти мовам, що дозволяють переписувати методи, які ви використовуєте у себе, іншими бібліотеками; коли таке трапляється поведінка програми може бути непередбаченою.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Такі симптоми називають проблемою виразу (expression problem); дізнайтеся більше за посиланням http://en.wikipedia.org/wiki/Expression_problem
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  "Рядок документації описуючий протокол."
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +> ЗАУВАЖЕННЯ: Префікс «I» часто використовується для розрізнення протоколів та типів за іменем. В громаді Clojure розробників існує багато різних думок на рахунок того, як повинен використовуватись п
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +З точки зору користувача, функції протоколів — це звичайні функції, що створені у тому ж просторі імен де і сам протокол. Це дає простий та легкий спосіб уникнення конфліктів між протоколами з однако
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Майже завжди ви будете використовувати макроси `extend-protocol` або `extend-type`. Ось як виглядає синтаксис `extend-type`:
некоректне зауваження

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ви могли помітити, що ми використали символ `string` замість `js/String` коли розширювали протоколом тип рядок. Це тому, що типи з JavaScript не можна розширювати. Якщо ви спробуєте розширити тип `js
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +`extend-protocol` працює навпаки; маючи протокол, цей макрос дозволяє додати імплементацію до декількох типів одразу. Ось як виглядає синтаксис:
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Що тут відбувається? У цьому випадку тип `set` імплементує протокол `IFn`, що є абстракцією для функцій або всього, що може бути викликаним як функція. Таким чином `set` може бути використаний як пре
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Тепер ви можете використати регулярний вираз як предикату, наприклад в функції `filter`:
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Раніше ми говорили про протоколи, що вирішують часту проблему поліморфізму: визначення по типу. Та за деяких обставин протоколи можуть обмежувати. Для таких випадків існують _мультіметоди_.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +_Мультіметоди_ не обмежені визначенням по типу; вони дозволяють визначати по типам декількох аргументів та значенню. Вони також дозволяють утворювати спеціалізовані (ad-hoc) ієрархії. Як і протоколи,
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  у якого встановлено значення за замовчуванням `:en`"
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Анонімна функція у `defmulti` — функція, що визначає який з методів повинен бути викликаний. Ця функція буде викликана кожного разу, коли ми викликаємо `say-hello` і повинна повертати деяке значення,
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +  (str "Привіт " (:name person "Анонімний")))
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В _ClojureScript_ ієрархії використовуються для побудови відносин у системі. Ієрархії створюються як відносини між такими об'єктами як символи, ключові слова та типи.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +В залежності від ваших потреб ієрархії можна будувати локально чи глобально. Як і мультіметоди ієрархії не обмежені одним простором імен. Їх можна розширювати з будь-якого простору імен.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Глобальний простір імен більш обмежений, що зроблено навмисно. Ключові слова та символи, що не прив'язані до простору імен не можуть бути використані у глобальній ієрархії. Така поведінка допомагає у
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Ми створили набір зв'язків між іменованими ключовими словами. У цьому випадку `::circle` та `::box` є дочірніми для `::shape`.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Як ви можете бачити, в локальних ієрархіях ми можемо використовувати нормальні (не іменовані) ключові слова, а функція `isa?` повертає `false` якщо в неї не передати ієрархію.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Однією із значних переваг ієрархій є те, що вони дуже добре працюють з мультіметодами. Мультіметоди використовують функцію `isa?` на останньому етапі визначення методу.
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Давайте розглянемо приклад щоб зрозуміти, що це означає. Спочатку ми створюємо мультіметод за допомогою форми `defmulti`:
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Тепер подивимось, що відбудеться коли ми викличемо мультіметод:
fixed

2017-06-05 11:49 UTC, denysdovhan commented on manuscript/03-13-Abstractions-and-Polymorphism.md
> +Все працює як і очікувалось; мультіметод викликає імплементацію по ключовому слову `:box`. Тепер подивимось, що буде якщо викликати мультіметод з ключовим словом `:circle`, для якого імплементація ві
fixed

2017-06-05 11:50 UTC, merged