04 03 closure library
LambdaBooks/clojurescript-unraveled pull request #72
Opened 2017-09-02 17:38 UTC by AMashoshyna

issue #25 
translation by @roman01la

2017-09-14 17:22 UTC, Mariannach requested changes

2017-09-14 17:22 UTC, Mariannach commented on manuscript/04-03-The-Closure-Library.md
> +Google Closure Library — це бібліотека на JavaScript, розроблена в Google. Це модульна бібліотека з набором функцій для роботи з DOM та подіями в DOM, Ajax і JSON та багатьма іншими функціями.
` Це модульна бібліотека з набором функцій` - Вона являє собою модульну бібліотеку з набором функцій ..

2017-09-14 17:22 UTC, Mariannach commented on manuscript/04-03-The-Closure-Library.md
> +Бібліотека Google Closure Library написана з орієнтацією на максимальну сумісність із компілятором Closure Compiler (компілятор _ClojureScript_ потребує його для роботи).
Бібліотека Google Closure Library **орієнтована** на максимальну сумісність із компілятором Closure Compiler

2017-09-14 17:22 UTC, Mariannach commented on manuscript/04-03-The-Closure-Library.md
> +Мова _ClojureScript_ та її компілятор використовують Google Closure Compiler та бібліотеку Closure. Простори імен _ClojureScript_ — це фактично модулі, сумісні з Closure. Це означає, що з бібліотекою
**Тобто** з бібліотекою Closure можна працювати майже так само, як

2017-09-17 18:10 UTC, alexclosed commented on manuscript/04-03-The-Closure-Library.md
> +Також бібліотека Closure надає доступ до спеціальних модулів, що поводяться як класи або об'єкти. Щоб імпортувати такі модулі в формі `(ns...)`, використовують директиву `:import`:
Також,(!)

2017-09-17 18:10 UTC, alexclosed commented on manuscript/04-03-The-Closure-Library.md
> +В програмах на _Clojure_ директива `:import` використовується для імпортування класів з бібліотек батьківської платформи (Java), так само, як і в _ClojureScript_ з JavaScript. Але для імпортування ти
батьівської платформи(!) так само, як

2017-09-29 22:00 UTC, denysdovhan approved these changes

2017-09-29 22:01 UTC, merged